apiVersion: v1
kind: Template
metadata:
  name: selenium-standalone-chrome
  annotations:
    description: "A Selenium Standalone Chrome Node"
    iconClass: "icon-selenium"
    tags: "selenium,chrome,standalone"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: selenium-standalone-chrome
    name: selenium-standalone-chrome
  spec:
    type: ClusterIP
    ports:
    - name: web
      port: 4444
      targetPort: 4444
      protocol: TCP
    selector:
      app: selenium-standalone-chrome
- apiVersion: v1
  kind: Pod
  metadata:
    name: selenium-standalone-chrome
    labels:
      type: selenium-standalone
      app: selenium-standalone-chrome
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: ${JAVA_OPTS}
      - name: POOL_MAX
        value: ${POOL_MAX}
      image: selenium/standalone-chrome
      name: master
      ports:
      - containerPort: 4444
        protocol: TCP
parameters:
  - name: JAVA_OPTS
    description: Options to pass to the java command
    value: "-Xmx512m"
  - name: POOL_MAX
    description: Max thread count for incoming and outgoing connections
    value: "30000"
labels:
  selenium-standalone-chrome: master
  app: selenium-standalone-chrome
